### ISSUE TITLE
能否支持单.word文件

### ISSUE THREAD

**Issue by liufeifeiholy** [wibetter/word2html#1]
用了下， 好像--local只支持文件夹， 不支持.word文件呢，可以支持直接处理单文件嘛？

**Comment by liufeifeiholy** [comment]
![image](https://user-images.githubusercontent.com/38906917/47195335-0ce5be80-d38e-11e8-887b-f2f61fcc8f3f.png)

**Comment by wibetter** [comment]
感谢提供了一个很好的建议，现在已经支持单文件转换功能。
